# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'aruba'
  gem 'cucumber', '~> 9.0'
  gem 'database_cleaner-sequel', '~> 2.0'
  gem 'debug_me'
  gem 'pry-stack_explorer'
  gem 'psych'
  gem 'rdoc'
  gem 'reline'
  gem 'rspec', '~> 3.10'
  gem 'rubocop'
  gem 'rubocop-factory_bot'
  gem 'rubocop-minitest'
  gem 'rubocop-packaging'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-sequel'
  gem 'rubocop-shopify'
  gem 'rubocop-thread_safety'
  gem 'ruby-lsp'
  gem 'solargraph'
end

gemspec

# Default gems for ruby CLI development

gem 'pry'
gem 'pry-doc'

# gem "sublayer"
gem 'agentic'
gem 'aia'
gem 'ai-agents'
gem 'algorithms'
gem 'amazing_print'
gem 'async'
gem 'bm25f'
gem 'circuit_breaker'
gem 'curses'
gem 'daru'
gem 'daru-view'
gem 'dotenv'
gem 'falcon'
gem 'fiddle'
gem 'front_matter_parser'
gem 'fuzzy_tools'
gem 'gemoji'
gem 'gli'
gem 'google-cloud-translate'
gem 'google-cloud-translate-v2'
gem 'google_custom_search_api'
gem 'google_search_results'
gem 'hashie'
gem 'highline'
gem 'hugging-face'
gem 'informers'
gem 'jongleur'
gem 'jsonl'
gem 'langchainrb'
gem 'lingua'
gem 'linguistics'
gem 'linkparser'
gem 'mimemagic'
gem 'mutex'
gem 'mutex_m'
gem 'nokogiri'
gem 'numpy'
gem 'ohm'
gem 'ohm-contrib'
gem 'oj'
gem 'ollama-ai'
gem 'open4'
gem 'open_router'
gem 'os'
gem 'parallel'
gem 'pastel'
gem 'pdf-reader'
gem 'pg'
gem 'pgvector'
gem 'poppler'
gem 'pragmatic_segmenter'
gem 'pragmatic_tokenizer'
gem 'prompt_manager'
gem 'pry-bond'
gem 'pycall'
gem 'ratelimit'
gem 'redcarpet'
gem 'redic'
gem 'redis'
gem 'redis-client'
gem 'regent'
gem 'ruby_llm'
gem 'ruby_llm-mcp'
gem 'ruby-spacy'
gem 'rubyzip'
gem 'sass'
gem 'sequel'
gem 'sequel_pg'
gem 'slim'
gem 'sprockets'
gem 'srt'
gem 'terrapin'
gem 'tf-idf-similarity'
gem 'thor'
gem 'timeout'
gem 'tokenizers'
gem 'webvtt'
gem 'wordnet'
gem 'wordnet-defaultdb'
gem 'yajl-ruby', require: 'yajl'
gem 'yaml'

# CLI and UI
gem 'tty-box'
gem 'tty-command'
gem 'tty-config'
gem 'tty-editor'
gem 'tty-exit'
gem 'tty-file'
gem 'tty-font'
gem 'tty-link'
gem 'tty-logger'
gem 'tty-markdown'
gem 'tty-option'
gem 'tty-prompt'
gem 'tty-screen'
gem 'tty-spinner'
gem 'tty-table'
gem 'tty-tree'
gem 'tty-which'
